### ISSUE TITLE
Plotly Dash Does Not Support Pub/Sub

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom-dash#2]
Because Plotly Dash does not support a pub/sub model for syncing state between the server and client we need a Flask server extension that will create a websocket route for the client to connect and subscribe to for updates.

**Comment by sylvoslee** [comment]
Any good news？

**Comment by rmorshea** [comment]
There is! I've managed to implement a Flask server extension for IDOM:

https://github.com/idom-team/idom/pull/275

I just haven't had time to integrate it here yet.

**Comment by rmorshea** [comment]
@sylvoslee this should be working now.

Note the different server invocation though via `idom_plotly_dash.run_server` since Werkzueg's dev server doesn't support web sockets.

I also think I'm going to rename this repo and package to `idom-dash` and `idom_dash` respectively since that seems to be the convention among other Dash components.

![plotly-dash](https://user-images.githubusercontent.com/4041990/105962571-dc912e00-6034-11eb-94c8-e19d8e7e357b.gif)

**Comment by sylvoslee** [comment]
`package_names_to_install={'victory', 'idom-client-react', 'react', '@material-ui/core', 'react-dom'}
web_module_names()={'victory', 'idom-client-react', 'react', 'htm', '@material-ui\\core', 'react-dom'}
Traceback (most recent call last):
  File "usage.py", line 13, in <module>
    material_ui = idom.install("@material-ui/core", fallback="loading...")
  File "C:\Users\Miniconda3\envs\debug\lib\site-packages\idom\client\module.py", line 40, in install
    manage.build(packages)
  File "C:\Users\Miniconda3\envs\debug\lib\site-packages\idom\client\manage.py", line 120, in build
    raise RuntimeError(  # pragma: no cover
RuntimeError: Successfuly installed ['victory', 'idom-client-react', 'react', '@material-ui/core', 'react-dom'] but failed to discover ['@material-ui/core'] post-install.`

**Comment by sylvoslee** [comment]
'''
package_names_to_install={'victory', 'idom-client-react', 'react', '@material-ui/core', 'react-dom'}
web_module_names()={'victory', 'idom-client-react', 'react', 'htm', '@material-ui\\core', 'react-dom'}
Traceback (most recent call last):
  File "usage.py", line 13, in <module>
    material_ui = idom.install("@material-ui/core", fallback="loading...")
  File "C:\Users\weiming.li\Miniconda3\envs\debug\lib\site-packages\idom\client\module.py", line 40, in install
    manage.build(packages)
  File "C:\Users\weiming.li\Miniconda3\envs\debug\lib\site-packages\idom\client\manage.py", line 120, in build
    raise RuntimeError(  # pragma: no cover
RuntimeError: Successfuly installed ['victory', 'idom-client-react', 'react', '@material-ui/core', 'react-dom'] but failed to discover ['@material-ui/core'] post-install.
'''

**Comment by sylvoslee** [comment]
yes ,it can work now,thank you for your great work!
When I test material ui button on Windows10,get some error like this:
```
package_names_to_install={'victory', 'idom-client-react', 'react', '@material-ui/core', 'react-dom'}
web_module_names()={'victory', 'idom-client-react', 'react', 'htm', '@material-ui\\core', 'react-dom'}
Traceback (most recent call last):
  File "usage.py", line 13, in <module>
    material_ui = idom.install("@material-ui/core", fallback="loading...")
  File "C:\Users\Miniconda3\envs\debug\lib\site-packages\idom\client\module.py", line 40, in install
    manage.build(packages)
  File "C:\Users\Miniconda3\envs\debug\lib\site-packages\idom\client\manage.py", line 120, in build
    raise RuntimeError(  # pragma: no cover
RuntimeError: Successfuly installed ['victory', 'idom-client-react', 'react', '@material-ui/core', 'react-dom'] but failed to discover ['@material-ui/core'] post-install.
```
I try to modify `material_ui = idom.install("@material-ui/core", fallback="loading...")`  to `material_ui = idom.install("@material-ui\\core", fallback="loading...")`, it still doesn't work

```
material_ui = idom.install("@material-ui\\core", fallback="loading...")

@idom.component
def material_ui_button():
    return material_ui.Button(
            {"color": "primary", "variant": "contained"}, "Hello World!"
        )
    
@idom.component
def ClickCount():
    count, set_count = idom.hooks.use_state(0)
    return idom.html.button({"onClick": lambda event: set_count(count + 1)}, count)

app.layout = html.Div(
    [
        html.H1("Simple Click Counter1"),
        html.Div(create_component(ClickCount)),
        html.Br(),
        html.H1("Installed Component (victory.js)"),
        create_component(victory.VictoryBar, {"style": {"parent": {"width": "500px"}}}),
        html.Br(),
        create_component(material_ui_button),
    ]
)
```

**Comment by rmorshea** [comment]
Hmm this looks like an issue with `idom` in general on Windows. Could you post this issue here: https://github.com/idom-team/idom/issues

**Comment by rmorshea** [comment]
Also, my test infra does not work under Windows so I may need some extra help debugging this since I myself don't have a windows machine available to me.

Going to close for now though and we can pick up again in the new issue you post.
